### ISSUE TITLE
Some questions about reconstruction loss 

### ISSUE THREAD

**Issue by tom68-ll** [Bin199/InforMin-CL#1]
Hi authors,
When discarding irrelevant information using the minimization of information entropy, it seems that the implementation of this part has been commented out.  Should we uncomment the following line when running the code?
https://github.com/ShaobinChen-AH/InforMin-CL/blob/8f1b2b241c3491b409345a745d7c799fe66e6646/informin-cl/models.py#L253

**Comment by ShaobinChen-AH** [comment]
Yes. And we have updated the code to make it more readable.
